
services:

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "16379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
       - "15673:5672"      # AMQP
       - "25673:15672"     # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: bank_user
      RABBITMQ_DEFAULT_PASS: bank_pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
