version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "6001:5672"    # AMQP   
      - "16001:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: bank_user
      RABBITMQ_DEFAULT_PASS: bank_pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:

